// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"FoodGuides/service/foodmanage/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/food/search",
				Handler: SearchHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/food/addfood",
				Handler: AddFoodHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/food/deletefood",
				Handler: DeleteFoodHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/food/foodlist",
				Handler: FoodListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
