// Code generated by goctl. DO NOT EDIT.
package types

type SearchRequest struct {
	Key string `json:"key"`
}

type SearchResponse struct {
	FoodReply
}

type AddFoodRequest struct {
	FoodId string `json:"foodId"`
}

type AddFoodResponse struct {
}

type DeleteFoodRequest struct {
	FoodId string `json:"foodId"`
}

type DeleteFoodResponse struct {
}

type FoodReply struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Protein      string `json:"protein"`
	Fat          string `json:"fat"`
	Carbohydrate string `json:"carbohydrate"`
	Calorie      string `json:"calorie"`
	Minerals     string `json:"minerals"`
	Calcium      string `json:"calcium"`
	Phosphorus   string `json:"phosphorus"`
	Iron         string `json:"iron"`
	Purine       string `json:"purine"`
}

type FoodListResponse struct {
	List []FoodReply `json:"list"`
}
