// Code generated by goctl. DO NOT EDIT.
// Source: food.proto

package server

import (
	"context"

	"FoodGuides/service/foodmanage/rpc/food"
	"FoodGuides/service/foodmanage/rpc/internal/logic"
	"FoodGuides/service/foodmanage/rpc/internal/svc"
)

type FoodServer struct {
	svcCtx *svc.ServiceContext
	food.UnimplementedFoodServer
}

func NewFoodServer(svcCtx *svc.ServiceContext) *FoodServer {
	return &FoodServer{
		svcCtx: svcCtx,
	}
}

func (s *FoodServer) Search(ctx context.Context, in *food.SearchRequest) (*food.FoodInfoResponse, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}

func (s *FoodServer) AddFood(ctx context.Context, in *food.AddFoodRequest) (*food.StatusResponse, error) {
	l := logic.NewAddFoodLogic(ctx, s.svcCtx)
	return l.AddFood(in)
}

func (s *FoodServer) DeleteFood(ctx context.Context, in *food.DeleteFoodRequest) (*food.StatusResponse, error) {
	l := logic.NewDeleteFoodLogic(ctx, s.svcCtx)
	return l.DeleteFood(in)
}

func (s *FoodServer) FoodList(ctx context.Context, in *food.FoodListRequest) (*food.FoodListResponse, error) {
	l := logic.NewFoodListLogic(ctx, s.svcCtx)
	return l.FoodList(in)
}
